server:
  port: 8040
spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.hukun.entity