server:
  port: 8040
spring:
  application:
    name: menu
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  datasource:
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hukun.entity
